#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ApiErrorError' {
    Context 'ApiErrorError' {
        It 'Initialize-ApiErrorError' {
            # a simple test to create an object
            #$NewObject = Initialize-ApiErrorError -Code "TEST_VALUE" -Message "TEST_VALUE" -InnerError "TEST_VALUE"
            #$NewObject | Should -BeOfType ApiErrorError
            #$NewObject.property | Should -Be 0
        }
    }
}
