#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CatalogTemplates' {
    Context 'CatalogTemplates' {
        It 'Initialize-CatalogTemplates' {
            # a simple test to create an object
            #$NewObject = Initialize-CatalogTemplates -OdataContext "TEST_VALUE" -OdataCount "TEST_VALUE" -Value "TEST_VALUE"
            #$NewObject | Should -BeOfType CatalogTemplates
            #$NewObject.property | Should -Be 0
        }
    }
}
