#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CatalogTemplateTemplateConfiguration' {
    Context 'CatalogTemplateTemplateConfiguration' {
        It 'Initialize-CatalogTemplateTemplateConfiguration' {
            # a simple test to create an object
            #$NewObject = Initialize-CatalogTemplateTemplateConfiguration -Id "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -PictureUrl "TEST_VALUE" -Language "TEST_VALUE" -Enabled "TEST_VALUE" -System "TEST_VALUE" -Singleton "TEST_VALUE" -DomId "TEST_VALUE" -Approval "TEST_VALUE" -PermanentMembership "TEST_VALUE" -AudienceTargeting "TEST_VALUE"
            #$NewObject | Should -BeOfType CatalogTemplateTemplateConfiguration
            #$NewObject.property | Should -Be 0
        }
    }
}
