#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CatalogTemplateTemplateConfigurationAudienceTargeting' {
    Context 'CatalogTemplateTemplateConfigurationAudienceTargeting' {
        It 'Initialize-CatalogTemplateTemplateConfigurationAudienceTargeting' {
            # a simple test to create an object
            #$NewObject = Initialize-CatalogTemplateTemplateConfigurationAudienceTargeting -Enabled "TEST_VALUE" -RulesWithTags "TEST_VALUE" -Rules "TEST_VALUE"
            #$NewObject | Should -BeOfType CatalogTemplateTemplateConfigurationAudienceTargeting
            #$NewObject.property | Should -Be 0
        }
    }
}
