#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CatalogTemplate' {
    Context 'CatalogTemplate' {
        It 'Initialize-CatalogTemplate' {
            # a simple test to create an object
            #$NewObject = Initialize-CatalogTemplate -TemplateConfiguration "TEST_VALUE" -ClonedTeam "TEST_VALUE" -NewTeam "TEST_VALUE"
            #$NewObject | Should -BeOfType CatalogTemplate
            #$NewObject.property | Should -Be 0
        }
    }
}
