#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'HookSignature' {
    Context 'HookSignature' {
        It 'Initialize-HookSignature' {
            # a simple test to create an object
            #$NewObject = Initialize-HookSignature -OdataContext "TEST_VALUE" -Signature "TEST_VALUE"
            #$NewObject | Should -BeOfType HookSignature
            #$NewObject.property | Should -Be 0
        }
    }
}
