#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'HookSignatureRequest' {
    Context 'HookSignatureRequest' {
        It 'Initialize-HookSignatureRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-HookSignatureRequest -Secret "TEST_VALUE" -Payload "TEST_VALUE"
            #$NewObject | Should -BeOfType HookSignatureRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
