#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'Hook' {
    Context 'Hook' {
        It 'Initialize-Hook' {
            # a simple test to create an object
            #$NewObject = Initialize-Hook -Id "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -Active "TEST_VALUE" -Events "TEST_VALUE" -Config "TEST_VALUE"
            #$NewObject | Should -BeOfType Hook
            #$NewObject.property | Should -Be 0
        }
    }
}
