#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RejectedApprovalResponsePayload' {
    Context 'RejectedApprovalResponsePayload' {
        It 'Initialize-RejectedApprovalResponsePayload' {
            # a simple test to create an object
            #$NewObject = Initialize-RejectedApprovalResponsePayload -Message "TEST_VALUE" -Approver "TEST_VALUE"
            #$NewObject | Should -BeOfType RejectedApprovalResponsePayload
            #$NewObject.property | Should -Be 0
        }
    }
}
