#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TeamChannel' {
    Context 'TeamChannel' {
        It 'Initialize-TeamChannel' {
            # a simple test to create an object
            #$NewObject = Initialize-TeamChannel -Id "TEST_VALUE" -CreatedDateTime "TEST_VALUE" -DisplayName "TEST_VALUE" -Description "TEST_VALUE" -MembershipType "TEST_VALUE"
            #$NewObject | Should -BeOfType TeamChannel
            #$NewObject.property | Should -Be 0
        }
    }
}
