#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TeamProvisioningRequestTeam' {
    Context 'TeamProvisioningRequestTeam' {
        It 'Initialize-TeamProvisioningRequestTeam' {
            # a simple test to create an object
            #$NewObject = Initialize-TeamProvisioningRequestTeam -Name "TEST_VALUE" -Description "TEST_VALUE" -WelcomeMessage "TEST_VALUE" -Membership "TEST_VALUE"
            #$NewObject | Should -BeOfType TeamProvisioningRequestTeam
            #$NewObject.property | Should -Be 0
        }
    }
}
