#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TeamMessagingSettings' {
    Context 'TeamMessagingSettings' {
        It 'Initialize-TeamMessagingSettings' {
            # a simple test to create an object
            #$NewObject = Initialize-TeamMessagingSettings -AllowUserEditMessages "TEST_VALUE" -AllowUserDeleteMessages "TEST_VALUE" -AllowOwnerDeleteMessages "TEST_VALUE" -AllowTeamMentions "TEST_VALUE" -AllowChannelMentions "TEST_VALUE"
            #$NewObject | Should -BeOfType TeamMessagingSettings
            #$NewObject.property | Should -Be 0
        }
    }
}
