#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'Team' {
    Context 'Team' {
        It 'Initialize-Team' {
            # a simple test to create an object
            #$NewObject = Initialize-Team -OdataContext "TEST_VALUE" -Id "TEST_VALUE" -CreatedDateTime "TEST_VALUE" -DisplayName "TEST_VALUE" -Description "TEST_VALUE" -InternalId "TEST_VALUE" -Classification "TEST_VALUE" -Specialization "TEST_VALUE" -Visibility "TEST_VALUE" -WebUrl "TEST_VALUE" -IsArchived "TEST_VALUE" -IsMembershipLimitedToOwners "TEST_VALUE" -DiscoverySettings "TEST_VALUE" -MemberSettings "TEST_VALUE" -GuestSettings "TEST_VALUE" -MessagingSettings "TEST_VALUE" -FunSettings "TEST_VALUE"
            #$NewObject | Should -BeOfType Team
            #$NewObject.property | Should -Be 0
        }
    }
}
