#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TeamMembershipPayload' {
    Context 'TeamMembershipPayload' {
        It 'Initialize-TeamMembershipPayload' {
            # a simple test to create an object
            #$NewObject = Initialize-TeamMembershipPayload -User "TEST_VALUE" -Role "TEST_VALUE"
            #$NewObject | Should -BeOfType TeamMembershipPayload
            #$NewObject.property | Should -Be 0
        }
    }
}
