#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TeamGuestSettings' {
    Context 'TeamGuestSettings' {
        It 'Initialize-TeamGuestSettings' {
            # a simple test to create an object
            #$NewObject = Initialize-TeamGuestSettings -AllowCreateUpdateChannels "TEST_VALUE" -AllowDeleteChannels "TEST_VALUE"
            #$NewObject | Should -BeOfType TeamGuestSettings
            #$NewObject.property | Should -Be 0
        }
    }
}
