#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TeamDiscoverySettings' {
    Context 'TeamDiscoverySettings' {
        It 'Initialize-TeamDiscoverySettings' {
            # a simple test to create an object
            #$NewObject = Initialize-TeamDiscoverySettings -ShowInTeamsSearchAndSuggestions "TEST_VALUE"
            #$NewObject | Should -BeOfType TeamDiscoverySettings
            #$NewObject.property | Should -Be 0
        }
    }
}
