#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TeamChannelTab' {
    Context 'TeamChannelTab' {
        It 'Initialize-TeamChannelTab' {
            # a simple test to create an object
            #$NewObject = Initialize-TeamChannelTab -Id "TEST_VALUE" -DisplayName "TEST_VALUE" -Configuration "TEST_VALUE" -TeamsApp "TEST_VALUE" -SortOrderIndex "TEST_VALUE" -WebUrl "TEST_VALUE"
            #$NewObject | Should -BeOfType TeamChannelTab
            #$NewObject.property | Should -Be 0
        }
    }
}
