#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TeamProvisioningRequest' {
    Context 'TeamProvisioningRequest' {
        It 'Initialize-TeamProvisioningRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-TeamProvisioningRequest -Template "TEST_VALUE" -Team "TEST_VALUE" -Metadata "TEST_VALUE"
            #$NewObject | Should -BeOfType TeamProvisioningRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
