#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.1
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Updates made by the approver

.PARAMETER Name
Updated team name
.PARAMETER Description
Updated team description
.PARAMETER WelcomeMessage
Updated welcome message
.OUTPUTS

ApprovedApprovalResponsePayloadUpdates<PSCustomObject>
#>

function Initialize-ApprovedApprovalResponsePayloadUpdates {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${WelcomeMessage}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ApprovedApprovalResponsePayloadUpdates' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "name" = ${Name}
            "description" = ${Description}
            "welcomeMessage" = ${WelcomeMessage}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ApprovedApprovalResponsePayloadUpdates<PSCustomObject>

.DESCRIPTION

Convert from JSON to ApprovedApprovalResponsePayloadUpdates<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ApprovedApprovalResponsePayloadUpdates<PSCustomObject>
#>
function ConvertFrom-JsonToApprovedApprovalResponsePayloadUpdates {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ApprovedApprovalResponsePayloadUpdates' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ApprovedApprovalResponsePayloadUpdates
        $AllProperties = ("name", "description", "welcomeMessage")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "welcomeMessage"))) { #optional property not found
            $WelcomeMessage = $null
        } else {
            $WelcomeMessage = $JsonParameters.PSobject.Properties["welcomeMessage"].value
        }

        $PSO = [PSCustomObject]@{
            "name" = ${Name}
            "description" = ${Description}
            "welcomeMessage" = ${WelcomeMessage}
        }

        return $PSO
    }

}

