#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.3
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A positive approval response payload.

.PARAMETER Message
Approval response message
.PARAMETER Approver
No description available.
.PARAMETER Updates
No description available.
.OUTPUTS

ApprovedApprovalResponsePayload<PSCustomObject>
#>

function Initialize-ApprovedApprovalResponsePayload {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Message},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Approver},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Updates}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ApprovedApprovalResponsePayload' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "message" = ${Message}
            "approver" = ${Approver}
            "updates" = ${Updates}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ApprovedApprovalResponsePayload<PSCustomObject>

.DESCRIPTION

Convert from JSON to ApprovedApprovalResponsePayload<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ApprovedApprovalResponsePayload<PSCustomObject>
#>
function ConvertFrom-JsonToApprovedApprovalResponsePayload {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ApprovedApprovalResponsePayload' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ApprovedApprovalResponsePayload
        $AllProperties = ("message", "approver", "updates")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "message"))) { #optional property not found
            $Message = $null
        } else {
            $Message = $JsonParameters.PSobject.Properties["message"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "approver"))) { #optional property not found
            $Approver = $null
        } else {
            $Approver = $JsonParameters.PSobject.Properties["approver"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "updates"))) { #optional property not found
            $Updates = $null
        } else {
            $Updates = $JsonParameters.PSobject.Properties["updates"].value
        }

        $PSO = [PSCustomObject]@{
            "message" = ${Message}
            "approver" = ${Approver}
            "updates" = ${Updates}
        }

        return $PSO
    }

}

