#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

The template permanent membership policy.

.PARAMETER Members
Members of a permanent membership team, as an array of PermanentMember. See [https://developers.salestim.com/api/reference/Models/PermanentMember](https://developers.salestim.com/api/reference/Models/PermanentMember) for more information.
.PARAMETER Owners
Members of a permanent membership team, as an array of PermanentMember. See [https://developers.salestim.com/api/reference/Models/PermanentMember](https://developers.salestim.com/api/reference/Models/PermanentMember) for more information.
.OUTPUTS

CatalogTemplateTemplateConfigurationPermanentMembership<PSCustomObject>
#>

function Initialize-CatalogTemplateTemplateConfigurationPermanentMembership {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Members},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Owners}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => CatalogTemplateTemplateConfigurationPermanentMembership' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "members" = ${Members}
            "owners" = ${Owners}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CatalogTemplateTemplateConfigurationPermanentMembership<PSCustomObject>

.DESCRIPTION

Convert from JSON to CatalogTemplateTemplateConfigurationPermanentMembership<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CatalogTemplateTemplateConfigurationPermanentMembership<PSCustomObject>
#>
function ConvertFrom-JsonToCatalogTemplateTemplateConfigurationPermanentMembership {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => CatalogTemplateTemplateConfigurationPermanentMembership' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CatalogTemplateTemplateConfigurationPermanentMembership
        $AllProperties = ("members", "owners")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "members"))) { #optional property not found
            $Members = $null
        } else {
            $Members = $JsonParameters.PSobject.Properties["members"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "owners"))) { #optional property not found
            $Owners = $null
        } else {
            $Owners = $JsonParameters.PSobject.Properties["owners"].value
        }

        $PSO = [PSCustomObject]@{
            "members" = ${Members}
            "owners" = ${Owners}
        }

        return $PSO
    }

}

