#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.3
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A collection of templates from your corporate catalog. See [https://developers.salestim.com/api/reference/Models/CatalogTemplate](https://developers.salestim.com/api/reference/Models/CatalogTemplate) for more information.

.PARAMETER OdataContext
Odata context
.PARAMETER OdataCount
Number of templates in the collection
.PARAMETER Value
Array of catalog templates
.OUTPUTS

CatalogTemplates<PSCustomObject>
#>

function Initialize-CatalogTemplates {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${OdataContext},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${OdataCount},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Value}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => CatalogTemplates' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "@odata.context" = ${OdataContext}
            "@odata.count" = ${OdataCount}
            "value" = ${Value}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CatalogTemplates<PSCustomObject>

.DESCRIPTION

Convert from JSON to CatalogTemplates<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CatalogTemplates<PSCustomObject>
#>
function ConvertFrom-JsonToCatalogTemplates {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => CatalogTemplates' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CatalogTemplates
        $AllProperties = ("@odata.context", "@odata.count", "value")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "@odata.context"))) { #optional property not found
            $OdataContext = $null
        } else {
            $OdataContext = $JsonParameters.PSobject.Properties["@odata.context"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "@odata.count"))) { #optional property not found
            $OdataCount = $null
        } else {
            $OdataCount = $JsonParameters.PSobject.Properties["@odata.count"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "value"))) { #optional property not found
            $Value = $null
        } else {
            $Value = $JsonParameters.PSobject.Properties["value"].value
        }

        $PSO = [PSCustomObject]@{
            "@odata.context" = ${OdataContext}
            "@odata.count" = ${OdataCount}
            "value" = ${Value}
        }

        return $PSO
    }

}

