#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.1
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A HookSignatureRequest object comprised of the secret and payload.

.PARAMETER Secret
Webhook secret
.PARAMETER Payload
Webhook payload
.OUTPUTS

HookSignatureRequest<PSCustomObject>
#>

function Initialize-HookSignatureRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Secret},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Payload}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => HookSignatureRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($Secret -eq $null) {
            throw "invalid value for 'Secret', 'Secret' cannot be null."
        }

        if ($Payload -eq $null) {
            throw "invalid value for 'Payload', 'Payload' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "secret" = ${Secret}
            "payload" = ${Payload}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to HookSignatureRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to HookSignatureRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

HookSignatureRequest<PSCustomObject>
#>
function ConvertFrom-JsonToHookSignatureRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => HookSignatureRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in HookSignatureRequest
        $AllProperties = ("secret", "payload")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'secret' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "secret"))) {
            throw "Error! JSON cannot be serialized due to the required property 'secret' missing."
        } else {
            $Secret = $JsonParameters.PSobject.Properties["secret"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "payload"))) {
            throw "Error! JSON cannot be serialized due to the required property 'payload' missing."
        } else {
            $Payload = $JsonParameters.PSobject.Properties["payload"].value
        }

        $PSO = [PSCustomObject]@{
            "secret" = ${Secret}
            "payload" = ${Payload}
        }

        return $PSO
    }

}

