#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.1
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER ShowInTeamsSearchAndSuggestions
Is the team shown in search suggestions
.OUTPUTS

TeamDiscoverySettings<PSCustomObject>
#>

function Initialize-TeamDiscoverySettings {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${ShowInTeamsSearchAndSuggestions}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => TeamDiscoverySettings' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "showInTeamsSearchAndSuggestions" = ${ShowInTeamsSearchAndSuggestions}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to TeamDiscoverySettings<PSCustomObject>

.DESCRIPTION

Convert from JSON to TeamDiscoverySettings<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

TeamDiscoverySettings<PSCustomObject>
#>
function ConvertFrom-JsonToTeamDiscoverySettings {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => TeamDiscoverySettings' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in TeamDiscoverySettings
        $AllProperties = ("showInTeamsSearchAndSuggestions")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "showInTeamsSearchAndSuggestions"))) { #optional property not found
            $ShowInTeamsSearchAndSuggestions = $null
        } else {
            $ShowInTeamsSearchAndSuggestions = $JsonParameters.PSobject.Properties["showInTeamsSearchAndSuggestions"].value
        }

        $PSO = [PSCustomObject]@{
            "showInTeamsSearchAndSuggestions" = ${ShowInTeamsSearchAndSuggestions}
        }

        return $PSO
    }

}

