#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.1
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'AuditTrailsApi' {
    Context 'Get-AuditTrailRecords' {
        It 'Test Get-AuditTrailRecords' {
            #$TestResult = Get-AuditTrailRecords -AuditTrailCode "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-AuditTrails' {
        It 'Test Get-AuditTrails' {
            #$TestResult = Get-AuditTrails
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
