#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TeamsApi' {
    Context 'Add-TeamMember' {
        It 'Test Add-TeamMember' {
            #$TestResult = Add-TeamMember -TeamId "TEST_VALUE" -TeamMembershipPayload "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ArchiveTeam' {
        It 'Test Invoke-ArchiveTeam' {
            #$TestResult = Invoke-ArchiveTeam -TeamId "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-TeamChannel' {
        It 'Test New-TeamChannel' {
            #$TestResult = New-TeamChannel -TeamId "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-TeamChannelTab' {
        It 'Test New-TeamChannelTab' {
            #$TestResult = New-TeamChannelTab -TeamId "TEST_VALUE" -ChannelId "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-TeamProvisioningJob' {
        It 'Test New-TeamProvisioningJob' {
            #$TestResult = New-TeamProvisioningJob -TeamProvisioningRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeleteTeam' {
        It 'Test Invoke-DeleteTeam' {
            #$TestResult = Invoke-DeleteTeam -TeamId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-Team' {
        It 'Test Get-Team' {
            #$TestResult = Get-Team -TeamId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TeamChannelTabs' {
        It 'Test Get-TeamChannelTabs' {
            #$TestResult = Get-TeamChannelTabs -TeamId "TEST_VALUE" -ChannelId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TeamChannels' {
        It 'Test Get-TeamChannels' {
            #$TestResult = Get-TeamChannels -TeamId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TeamPrimaryChannel' {
        It 'Test Get-TeamPrimaryChannel' {
            #$TestResult = Get-TeamPrimaryChannel -TeamId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-UnarchiveTeam' {
        It 'Test Invoke-UnarchiveTeam' {
            #$TestResult = Invoke-UnarchiveTeam -TeamId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-Team' {
        It 'Test Update-Team' {
            #$TestResult = Update-Team -TeamId "TEST_VALUE" -Body "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
