#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.1
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TemplatesCatalogApi' {
    Context 'Get-CatalogTemplates' {
        It 'Test Get-CatalogTemplates' {
            #$TestResult = Get-CatalogTemplates -Language "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-MyCatalogTemplates' {
        It 'Test Get-MyCatalogTemplates' {
            #$TestResult = Get-MyCatalogTemplates -Language "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
