#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.1
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'WebhooksApi' {
    Context 'New-Hook' {
        It 'Test New-Hook' {
            #$TestResult = New-Hook -HookPayload "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeleteHook' {
        It 'Test Invoke-DeleteHook' {
            #$TestResult = Invoke-DeleteHook -HookId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-HookSignature' {
        It 'Test New-HookSignature' {
            #$TestResult = New-HookSignature -HookSignatureRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-HooksEvents' {
        It 'Test Get-HooksEvents' {
            #$TestResult = Get-HooksEvents
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
