#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.0.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ApprovalsApi' {
    Context 'Approve-TeamCreation' {
        It 'Test Approve-TeamCreation' {
            #$TestResult = Approve-TeamCreation -ApprovalRequestId "TEST_VALUE" -ApprovedApprovalResponsePayload "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Deny-TeamCreation' {
        It 'Test Deny-TeamCreation' {
            #$TestResult = Deny-TeamCreation -ApprovalRequestId "TEST_VALUE" -RejectedApprovalResponsePayload "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
