#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Webhook event

.PARAMETER Code
Webhook event code
.OUTPUTS

HookEvent<PSCustomObject>
#>

function Initialize-HookEvent {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Code}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => HookEvent' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "code" = ${Code}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to HookEvent<PSCustomObject>

.DESCRIPTION

Convert from JSON to HookEvent<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

HookEvent<PSCustomObject>
#>
function ConvertFrom-JsonToHookEvent {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => HookEvent' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in HookEvent
        $AllProperties = ("code")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "code"))) { #optional property not found
            $Code = $null
        } else {
            $Code = $JsonParameters.PSobject.Properties["code"].value
        }

        $PSO = [PSCustomObject]@{
            "code" = ${Code}
        }

        return $PSO
    }

}

