#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A negative approval response payload.

.PARAMETER Message
Approval response message
.PARAMETER Approver
No description available.
.OUTPUTS

RejectedApprovalResponsePayload<PSCustomObject>
#>

function Initialize-RejectedApprovalResponsePayload {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Message},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Approver}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => RejectedApprovalResponsePayload' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "message" = ${Message}
            "approver" = ${Approver}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to RejectedApprovalResponsePayload<PSCustomObject>

.DESCRIPTION

Convert from JSON to RejectedApprovalResponsePayload<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

RejectedApprovalResponsePayload<PSCustomObject>
#>
function ConvertFrom-JsonToRejectedApprovalResponsePayload {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => RejectedApprovalResponsePayload' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in RejectedApprovalResponsePayload
        $AllProperties = ("message", "approver")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "message"))) { #optional property not found
            $Message = $null
        } else {
            $Message = $JsonParameters.PSobject.Properties["message"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "approver"))) { #optional property not found
            $Approver = $null
        } else {
            $Approver = $JsonParameters.PSobject.Properties["approver"].value
        }

        $PSO = [PSCustomObject]@{
            "message" = ${Message}
            "approver" = ${Approver}
        }

        return $PSO
    }

}

