#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ApiErrorErrorInnerError' {
    Context 'ApiErrorErrorInnerError' {
        It 'Initialize-ApiErrorErrorInnerError' {
            # a simple test to create an object
            #$NewObject = Initialize-ApiErrorErrorInnerError -Date "TEST_VALUE" -RequestId "TEST_VALUE"
            #$NewObject | Should -BeOfType ApiErrorErrorInnerError
            #$NewObject.property | Should -Be 0
        }
    }
}
