#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ApiError' {
    Context 'ApiError' {
        It 'Initialize-ApiError' {
            # a simple test to create an object
            #$NewObject = Initialize-ApiError -OdataContext "TEST_VALUE" -VarError "TEST_VALUE"
            #$NewObject | Should -BeOfType ApiError
            #$NewObject.property | Should -Be 0
        }
    }
}
