#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ApprovedApprovalResponsePayload' {
    Context 'ApprovedApprovalResponsePayload' {
        It 'Initialize-ApprovedApprovalResponsePayload' {
            # a simple test to create an object
            #$NewObject = Initialize-ApprovedApprovalResponsePayload -Message "TEST_VALUE" -Approver "TEST_VALUE" -Updates "TEST_VALUE"
            #$NewObject | Should -BeOfType ApprovedApprovalResponsePayload
            #$NewObject.property | Should -Be 0
        }
    }
}
