#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ApprovalTeamMember' {
    Context 'ApprovalTeamMember' {
        It 'Initialize-ApprovalTeamMember' {
            # a simple test to create an object
            #$NewObject = Initialize-ApprovalTeamMember -Id "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType ApprovalTeamMember
            #$NewObject.property | Should -Be 0
        }
    }
}
