#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.1
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'AuditTrail' {
    Context 'AuditTrail' {
        It 'Initialize-AuditTrail' {
            # a simple test to create an object
            #$NewObject = Initialize-AuditTrail -Code "TEST_VALUE" -Category "TEST_VALUE" -Fields "TEST_VALUE"
            #$NewObject | Should -BeOfType AuditTrail
            #$NewObject.property | Should -Be 0
        }
    }
}
