#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CatalogTemplateClonedTeam' {
    Context 'CatalogTemplateClonedTeam' {
        It 'Initialize-CatalogTemplateClonedTeam' {
            # a simple test to create an object
            #$NewObject = Initialize-CatalogTemplateClonedTeam -TeamId "TEST_VALUE" -TeamName "TEST_VALUE" -IncludeApps "TEST_VALUE" -IncludeTabs "TEST_VALUE" -IncludeSettings "TEST_VALUE" -IncludeChannels "TEST_VALUE" -IncludeMembers "TEST_VALUE"
            #$NewObject | Should -BeOfType CatalogTemplateClonedTeam
            #$NewObject.property | Should -Be 0
        }
    }
}
