#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CatalogTemplateTemplateConfigurationApproval' {
    Context 'CatalogTemplateTemplateConfigurationApproval' {
        It 'Initialize-CatalogTemplateTemplateConfigurationApproval' {
            # a simple test to create an object
            #$NewObject = Initialize-CatalogTemplateTemplateConfigurationApproval -RequireApproval "TEST_VALUE" -ApprovalTeam "TEST_VALUE"
            #$NewObject | Should -BeOfType CatalogTemplateTemplateConfigurationApproval
            #$NewObject.property | Should -Be 0
        }
    }
}
