#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CatalogTemplateNewTeam' {
    Context 'CatalogTemplateNewTeam' {
        It 'Initialize-CatalogTemplateNewTeam' {
            # a simple test to create an object
            #$NewObject = Initialize-CatalogTemplateNewTeam -NamingConventionWithTags "TEST_VALUE" -EmailConventionWithTags "TEST_VALUE" -DescriptionConventionWithTags "TEST_VALUE" -WelcomeMessageConventionWithTags "TEST_VALUE" -NamingConvention "TEST_VALUE" -EmailConvention "TEST_VALUE" -DescriptionConvention "TEST_VALUE" -WelcomeMessageConvention "TEST_VALUE" -DefaultName "TEST_VALUE" -DefaultDescription "TEST_VALUE" -DefaultWelcomeMessage "TEST_VALUE" -TeamPrivacy "TEST_VALUE" -AddRequesterAsTeamOwner "TEST_VALUE"
            #$NewObject | Should -BeOfType CatalogTemplateNewTeam
            #$NewObject.property | Should -Be 0
        }
    }
}
