#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'CatalogTemplateTemplateConfigurationPermanentMembership' {
    Context 'CatalogTemplateTemplateConfigurationPermanentMembership' {
        It 'Initialize-CatalogTemplateTemplateConfigurationPermanentMembership' {
            # a simple test to create an object
            #$NewObject = Initialize-CatalogTemplateTemplateConfigurationPermanentMembership -Members "TEST_VALUE" -Owners "TEST_VALUE"
            #$NewObject | Should -BeOfType CatalogTemplateTemplateConfigurationPermanentMembership
            #$NewObject.property | Should -Be 0
        }
    }
}
