#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'HookPayload' {
    Context 'HookPayload' {
        It 'Initialize-HookPayload' {
            # a simple test to create an object
            #$NewObject = Initialize-HookPayload -Name "TEST_VALUE" -Description "TEST_VALUE" -Events "TEST_VALUE" -Config "TEST_VALUE"
            #$NewObject | Should -BeOfType HookPayload
            #$NewObject.property | Should -Be 0
        }
    }
}
