#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'HookEvent' {
    Context 'HookEvent' {
        It 'Initialize-HookEvent' {
            # a simple test to create an object
            #$NewObject = Initialize-HookEvent -Code "TEST_VALUE"
            #$NewObject | Should -BeOfType HookEvent
            #$NewObject.property | Should -Be 0
        }
    }
}
