#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'Job' {
    Context 'Job' {
        It 'Initialize-Job' {
            # a simple test to create an object
            #$NewObject = Initialize-Job -Id "TEST_VALUE" -Log "TEST_VALUE" -Type "TEST_VALUE" -Status "TEST_VALUE" -Progress "TEST_VALUE" -VarData "TEST_VALUE"
            #$NewObject | Should -BeOfType Job
            #$NewObject.property | Should -Be 0
        }
    }
}
