#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'Label' {
    Context 'Label' {
        It 'Initialize-Label' {
            # a simple test to create an object
            #$NewObject = Initialize-Label -Id "TEST_VALUE" -Name "TEST_VALUE" -Description "TEST_VALUE" -Color "TEST_VALUE" -Sensitivity "TEST_VALUE" -Tooltip "TEST_VALUE" -IsActive "TEST_VALUE" -Parent "TEST_VALUE"
            #$NewObject | Should -BeOfType Label
            #$NewObject.property | Should -Be 0
        }
    }
}
