#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TeamChannelTabTeamsApp' {
    Context 'TeamChannelTabTeamsApp' {
        It 'Initialize-TeamChannelTabTeamsApp' {
            # a simple test to create an object
            #$NewObject = Initialize-TeamChannelTabTeamsApp -Id "TEST_VALUE" -ExternalId "TEST_VALUE" -DisplayName "TEST_VALUE" -DistributionMethod "TEST_VALUE"
            #$NewObject | Should -BeOfType TeamChannelTabTeamsApp
            #$NewObject.property | Should -Be 0
        }
    }
}
