#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TeamFunSettings' {
    Context 'TeamFunSettings' {
        It 'Initialize-TeamFunSettings' {
            # a simple test to create an object
            #$NewObject = Initialize-TeamFunSettings -AllowGiphy "TEST_VALUE" -GiphyContentRating "TEST_VALUE" -AllowStickersAndMemes "TEST_VALUE" -AllowCustomMemes "TEST_VALUE"
            #$NewObject | Should -BeOfType TeamFunSettings
            #$NewObject.property | Should -Be 0
        }
    }
}
