#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TeamChannelTabConfiguration' {
    Context 'TeamChannelTabConfiguration' {
        It 'Initialize-TeamChannelTabConfiguration' {
            # a simple test to create an object
            #$NewObject = Initialize-TeamChannelTabConfiguration -EntityId "TEST_VALUE" -ContentUrl "TEST_VALUE" -WebsiteUrl "TEST_VALUE" -RemoveUrl "TEST_VALUE"
            #$NewObject | Should -BeOfType TeamChannelTabConfiguration
            #$NewObject.property | Should -Be 0
        }
    }
}
