#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TeamMemberSettings' {
    Context 'TeamMemberSettings' {
        It 'Initialize-TeamMemberSettings' {
            # a simple test to create an object
            #$NewObject = Initialize-TeamMemberSettings -AllowCreateUpdateChannels "TEST_VALUE" -AllowCreatePrivateChannels "TEST_VALUE" -AllowDeleteChannels "TEST_VALUE" -AllowAddRemoveApps "TEST_VALUE" -AllowCreateUpdateRemoveTabs "TEST_VALUE" -AllowCreateUpdateRemoveConnectors "TEST_VALUE"
            #$NewObject | Should -BeOfType TeamMemberSettings
            #$NewObject.property | Should -Be 0
        }
    }
}
