#
# SalesTim API
# The unified Microsoft Teams Governance API. Visit our [Tech Hub](https://developers.salestim.com/api/) for more information. 
# Version: 1.2.0
# Contact: support@salestim.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'Users' {
    Context 'Users' {
        It 'Initialize-Users' {
            # a simple test to create an object
            #$NewObject = Initialize-Users -OdataContext "TEST_VALUE" -OdataCount "TEST_VALUE" -Value "TEST_VALUE"
            #$NewObject | Should -BeOfType Users
            #$NewObject.property | Should -Be 0
        }
    }
}
