openapi: "3.0.2"

info:
  title: SalesTim API Explorer
  description: >
    API Explorer for the SalesTim API
  version: "1.0"
  termsOfService: https://www.salestim.com/legal/tos/
  contact:
    name: SalesTim Support
    email: support@salestim.com
    url: https://developers.salestim.com/api/
  license:
    name: (c) Copyright 2019-2020 SalesTim, all rights reserved.
    url: https://www.salestim.com/legal/eula

servers:
  - url: "https://api.salestim.io/v1.0"
    description: "SalesTim API endpoints"

paths:
  /plugins:
    post:
      tags:
        - plugins
      summary: Create a new plugin
      description: Create a new plugin and get its .
      operationId: createPlugin
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Plugin successfully created
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /store/templates:
    get:
      tags:
        - store
      summary: Get all store templates
      description: Get all store templates.
      operationId: getStoreTemplates
      responses:
        "200":
          description: Store templates successfully retreived
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /store/templates/{id}:
    get:
      tags:
        - store
      summary: Get a store template from its id
      description: Get a store template from its id.
      operationId: getStoreTemplate
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The template ID
      responses:
        "200":
          description: Store template successfully retrieved
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /store/templates/bycategory/{id}:
    get:
      tags:
        - store
      summary: Get all store template from a specific category
      description: Get all store template from a specific category.
      operationId: getStoreTemplatesByCategory
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The category ID
      responses:
        "200":
          description: Store templates successfully retrieved
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /store/categories:
    get:
      tags:
        - store
      summary: Get all store categories
      description: Get all categories from the template store.
      operationId: getStoreCategories
      responses:
        "200":
          description: Store categories successfully retreived
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "500":
          $ref: "#/components/responses/InternalServerError"

tags:
  - name: store
    description: Teams templates store
    externalDocs:
      url: https://developers.salestim.com

components:
  # 1) Define the security scheme type (HTTP bearer)
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
      description: A valid Azure AD access_token
    pluginId:
      type: apiKey
      in: header
      name: X-PLUGIN-ID
      description: A valid plugin ID obtained by a POST to /plugins
    pluginSecret: # arbitrary name for the security scheme
      type: apiKey
      in: header # can be "header", "query" or "cookie"
      name: X-PLUGIN-SECRET # name of the header, query parameter or cookie
      description: A valid plugin secret obtained by a POST to /plugins 
  responses:
    UnauthorizedError:
      description: API key or app id are missing or invalid

    NotFoundError:
      description: The ressource cannot be found

    InternalServerError:
      description: The server encountered an unexpected condition that prevented it from fulfilling the request.
